### ISSUE TITLE
401 unauthorized during check sync status

### ISSUE THREAD

**Issue by maurbeck** [chaeplin/dashmnb#42]
I'm getting the following response when I run dashmnb.py using port 9998:
`Network : MAINNET
--> get dash explorer block count
--> get dashd status

--> checking syncing status 

version  : 0.3.rc8
caller   : check_dashd_syncing
function : rpcgetinfo
err      : ("non-JSON HTTP response with '401 Unauthorized' from server",) ===> Dash-QT or dashd running ?`

Is this a 401 from my local Dash-QT to dashmnb, or a 401 from my remote node server to my local Dash-QT?

**Comment by chaeplin** [comment]
with `get dashd status`, dashmnb uses local or remote dashd.

1) if dashd is local(127.0.0.1), check rpcuser and rpcpassword(config.py and dash.conf of dashd)
2) if dashd is remote(ssh tunnel), check ssh tunnel and check rpcuser and rpcpassword(config.py and dash.conf of dashd)

---> https://github.com/chaeplin/dashmnb/blob/master/dashlib/config.sample.mainnet.py

3) you can use my remote rpvsvc 
---> https://github.com/chaeplin/dashmnb/blob/master/dashlib/config.sample.mainnet.remotesvc.py

**Comment by maurbeck** [comment]
Thanks. Although the rcpuser and password can vary from the local Dash-QT and the server, the dashmnb script and Dash-QT need to match.  Those are matched up and auth occurred. Waiting for a re-index now. Thanks.
